version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Docker 소켓 마운트
    networks:
      - my-network

  backend:
    image: my-backend-app:latest
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:

volumes:
  jenkins_home:
